// <auto-generated />
using System;
using DreamTech_Ecommerce.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamTech_Ecommerce.Migrations
{
    [DbContext(typeof(DreamAppContext))]
    [Migration("20231203142529_InitiateDB")]
    partial class InitiateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DreamTech_Ecommerce.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "laptop",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = "laptop-gaming",
                            Name = "Laptop Gaming"
                        },
                        new
                        {
                            Id = "pc",
                            Name = "PC"
                        },
                        new
                        {
                            Id = "apple",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = "main-cpu-vga",
                            Name = "Main - CPU - VGA"
                        },
                        new
                        {
                            Id = "man-hinh",
                            Name = "Màn hình"
                        },
                        new
                        {
                            Id = "ban-phim",
                            Name = "Bàn phím"
                        },
                        new
                        {
                            Id = "chuot-lot-chuot",
                            Name = "Chuột - Lót chuột"
                        },
                        new
                        {
                            Id = "phu-kien",
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = "phan-mem-mang",
                            Name = "Phần mềm + Mạng"
                        },
                        new
                        {
                            Id = "tai-nghe-loa",
                            Name = "Tai nghe - Loa"
                        });
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiscountRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiftName = "Màn hình MSI OPTIX MAG274QRX 27\" IPS 2K 240Hz G-Sync chuyên game",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn",
                            Type = 1,
                            Value = 9390000
                        },
                        new
                        {
                            Id = 2,
                            GiftName = "Móc khóa Keycap GearVN",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn",
                            Type = 1,
                            Value = 99000
                        },
                        new
                        {
                            Id = 3,
                            GiftName = "Áo khoác (bomber)",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn",
                            Type = 1,
                            Value = 300000
                        },
                        new
                        {
                            Id = 4,
                            GiftName = "Áo khoác (bomber)",
                            ProductId = "laptop-asus-expertbook-b1400ceae-bv3186w",
                            Type = 1,
                            Value = 300000
                        });
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DiscountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Battery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalePrice")
                        .HasColumnType("int");

                    b.Property<string>("Screen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "laptop-asus-expertbook-b1400ceae-bv3186w",
                            Battery = "42WHrs, 3S1P, 3-cell Li-ion",
                            Brand = "Asus",
                            CategoryId = "laptop",
                            Color = "Black",
                            Cpu = "Intel Core i3-1115G4 3.0 GHz (6M Cache, up to 4.1 GHz, 2 cores)",
                            Description = "là một chiếc laptop văn phòng chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "256GB PCIE G3 SSD (Còn trống 1 khe 2.5\" HDD up to 1TB)",
                            Name = "Laptop Asus ExpertBook B1400CEAE BV3186W",
                            Price = 14990000,
                            QtyInStock = 10,
                            Ram = "12GB DDR4 3200MHz (4GB onboard + 8GB Gearvn tặng)\r\nNâng cấp tối đa 36GB",
                            SalePrice = 8990000,
                            Screen = "14.0 HD (1366X768) 16:9 220nits, Anti-Glare NTSC:45% ",
                            Size = "32.34 x 21.56 x 1.92 ~ 1.92 cm",
                            Vga = "Intel® UHD Graphics",
                            Weight = "1.45 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn",
                            Battery = "4 Cell 99.9WHrs",
                            Brand = "MSI",
                            CategoryId = "laptop-gaming",
                            Color = "Selenite Gray",
                            Cpu = "Intel Core i9-13900H 4.1GHz up to 5.4GHz, 14 Cores 20 Threads ,24MB Cache",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "2TB SSD PCIE G4X4 (2 slots M.2 NVMe PCIe Gen4)",
                            Name = "Laptop Gaming MSI Stealth 16 Mercedes AMG A13VG 289VN",
                            Price = 80990000,
                            QtyInStock = 10,
                            Ram = "32GB (16x2) DDR5 5200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 74990000,
                            Screen = "16\" UHD+ (3840x2400), 16:10, 100% DCI-P3, OLED, DisplayHDR True Black 600",
                            Size = "355.8 x 259.7 x 19.95 (mm)",
                            Vga = "NVIDIA® GeForce RTX™ 4070 8GB GDDR6 + MUX Switch",
                            Weight = "1.88 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-msi-gf63-12ucx-841vn",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "MSI",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "Intel Core i5-12450H 3.3GHz up to 4.40GHz 12MB, 8 nhân, 12 luồng",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming MSI GF63 12UCX 841VN",
                            Price = 17990000,
                            QtyInStock = 10,
                            Ram = "8GB (8x1) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 15990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-msi-gf63-12uc-887vn",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "MSI",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "Intel Core i5-12450H 3.3GHz up to 4.40GHz 12MB, 8 nhân, 12 luồng",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming MSI GF63 12UC 887VN",
                            Price = 20990000,
                            QtyInStock = 10,
                            Ram = "8GB (8x1) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 19790000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-lenovo-legion-slim-5-16irh8-82ya00buvn",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "Lenovo",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "Intel Core i5-12450H 3.3GHz up to 4.40GHz 12MB, 8 nhân, 12 luồng",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming Lenovo Legion Slim 5 16IRH8 82YA00BUVN",
                            Price = 43990000,
                            QtyInStock = 10,
                            Ram = "8GB (8x1) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 41990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-lenovo-loq-15irh8-82xv00qqvn",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "Lenovo",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "Intel Core i5-12450H 3.3GHz up to 4.40GHz 12MB, 8 nhân, 12 luồng",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming Lenovo LOQ 15IRH8 82XV00QQVN",
                            Price = 20990000,
                            QtyInStock = 10,
                            Ram = "8GB (8x1) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 18990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-acer-predator-helios-300-ph315-55-76kg",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "Acer Predato",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "Intel Core i5-12450H 3.3GHz up to 4.40GHz 12MB, 8 nhân, 12 luồng",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming Acer Predator Helios 300 PH315 55 76KG",
                            Price = 48490000,
                            QtyInStock = 10,
                            Ram = "8GB (8x1) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)",
                            SalePrice = 30990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "laptop-gaming-asus-tuf-a15-fa507nu-lp031w",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "ASUS",
                            CategoryId = "laptop-gaming",
                            Color = "Silver",
                            Cpu = "R7-7735HS",
                            Description = "là một chiếc laptop gaming chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Laptop gaming ASUS TUF A15 FA507NU LP031W",
                            Price = 30490000,
                            QtyInStock = 10,
                            Ram = "16 GB",
                            SalePrice = 25990000,
                            Screen = "15.6 inch FHD",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-amd-r5-7600-vga-rtx-4060",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "R5 7600",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN AMD R5-7600/ VGA RTX 4060",
                            Price = 26480000,
                            QtyInStock = 10,
                            Ram = "16GB",
                            SalePrice = 25990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-x-asus-evangelion-2",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "R5 7600",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN x ASUS EVANGELION 2",
                            Price = 130000000,
                            QtyInStock = 10,
                            Ram = "16GB",
                            SalePrice = 125000000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-intel-i7-13700f-vga-rtx-4060-ti",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "i7 13700F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN Intel i7-13700F/ VGA RTX 4060 Ti",
                            Price = 33920000,
                            QtyInStock = 10,
                            Ram = "16GB",
                            SalePrice = 33890000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "Nvidia Geforce RTX 2050 4GB GDDR6",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-intel-i5-13600kf-vga-rtx-3060",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "i5 13600KF",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN Intel i5-13600KF/ VGA RTX 3060",
                            Price = 29510000,
                            QtyInStock = 10,
                            Ram = "16GB",
                            SalePrice = 28990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "RTX 3060",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-intel-i7-13700f-vga-rtx-4070",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "i7 13700F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN Intel i7-13700F/ VGA RTX 4070",
                            Price = 59990000,
                            QtyInStock = 10,
                            Ram = "16GB",
                            SalePrice = 58990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "RTX 4070",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-intel-i5-12400f-vga-rtx-4060",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "i5 12400F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN Intel i5-12400F/ VGA RTX 4060",
                            Price = 24990000,
                            QtyInStock = 10,
                            Ram = "8GB",
                            SalePrice = 24490000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "RTX 4070",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "pc-gvn-intel-i3-12100f-vga-gtx-1650",
                            Battery = "3 Cell 52.4 WHr",
                            Brand = "GVN",
                            CategoryId = "pc",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "PC GVN Intel i3-12100F/ VGA GTX 1650",
                            Price = 11590000,
                            QtyInStock = 10,
                            Ram = "8GB",
                            SalePrice = 10890000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-logitech-g502-x-plus-lightspeed-white",
                            Battery = "Pin sạc",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Logitech G502 X Plus LightSpeed White",
                            Price = 3890000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 3190000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-razer-basilisk-v3",
                            Battery = "Không",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Razer Basilisk V3",
                            Price = 1990000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 990000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-logitech-g-pro-x-superlight-wireless-red",
                            Battery = "Pin sạc",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Logitech G Pro X Superlight Wireless Red",
                            Price = 3590000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 2850000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-logitech-g102-lightsync-black",
                            Battery = "Không",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Logitech G102 LightSync Black",
                            Price = 599000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 399000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-logitech-g304-wireless-white",
                            Battery = "Pin sạc",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Logitech G304 Wireless White",
                            Price = 1090000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 780000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        },
                        new
                        {
                            Id = "chuot-logitech-g304-wireless",
                            Battery = "Pin rời",
                            Brand = "Logitech",
                            CategoryId = "chuot-lot-chuot",
                            Color = "Silver",
                            Cpu = "i3 12100F",
                            Description = "là một chiếc PC chất lượng cao với hiệu suất khủng từ CPU thế hệ thứ 11, ổ lưu trữ khủng cho khả năng xử lý ổn định. Nếu bạn đang tìm kiếm một chiếc laptop giá rẻ dưới 10 triệu nhưng vẫn đáp ứng đầy đủ mọi nhu cầu từ học tập đến làm việc thì Asus Expert Book B1400CEAE BV3186W chính là nhân vật bạn đang tìm kiếm.",
                            Disk = "512GB NVMe PCIe Gen 4x4 SSD ( Còn trống 1 khe 2.5\" SATA)",
                            Name = "Chuột Logitech G304 Wireless",
                            Price = 1090000,
                            QtyInStock = 20,
                            Ram = "8GB",
                            SalePrice = 780000,
                            Screen = "15.6\" FHD (1920 x 1080) IPS 144Hz, Thin Bezel, 45%NTSC",
                            Size = "359 x 254 x 21.5 mm",
                            Vga = "GTX 1650",
                            Weight = "1.86 kg"
                        });
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/thumb_b1_25831d5fc18e45b1ada9ed3f184c9815_grande.png",
                            ProductId = "laptop-asus-expertbook-b1400ceae-bv3186w"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/gf63-final_6ce8b15400404b2baf9632d843a2c4c7.png",
                            ProductId = "laptop-gaming-msi-gf63-12ucx-841vn"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/gf63-final_6ce8b15400404b2baf9632d843a2c4c7_large_c22125bccefc4149b1b7321cfc2ed062.png",
                            ProductId = "laptop-gaming-msi-gf63-12uc-887vn"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/82ya00buvn_0cb35336843549dc8781c599c63c6ae1.png",
                            ProductId = "laptop-gaming-lenovo-legion-slim-5-16irh8-82ya00buvn"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/ava-msi_c758a76200904fb0868673020ba576ef_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/289vn_8952ee549ddd4d3b8b40a040f14a8799_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/2_3013d5c7b77447a2b1995e7845adc708_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/1_17f74834dacc4eb99ad85d3637bfae65_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/5_e40e921e99d34efc87e74d21d48ed60b_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/3_0be25d3df3b740dcbfb7e94d2e6e44d1_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/4_38ee6e60844747f3a780f8cbfc795678_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/8_cb852dc5c90744eeac825a0ab6d5bf3b_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/6_3c627c81fb874603b78c2bf77874b88f_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/7_e3db80007449400f9f4271cb2d14e170_grande.png",
                            ProductId = "laptop-gaming-msi-stealth-16-mercedes-amg-a13vg-289vn"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/82xv00qpvn_cb7cf3e1339a4fca857fc1b06d49d0f3_large_1240c22a67834dc4b2446439760ac870_medium.png",
                            ProductId = "laptop-gaming-lenovo-loq-15irh8-82xv00qqvn"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/76kg_1433e407838944df88bd906b57729c0a_medium.png",
                            ProductId = "laptop-gaming-acer-predator-helios-300-ph315-55-76kg"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/lp520w_dfddfcf4a46d43e4b82391209328e195_large_7fa59a1a8ef14c37b78bc34161b45a87_medium.png",
                            ProductId = "laptop-gaming-asus-tuf-a15-fa507nu-lp031w"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/cougar_2101a66491414b49a99fcd1e4e0421ad_medium.png",
                            ProductId = "pc-gvn-amd-r5-7600-vga-rtx-4060"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://file.hstatic.net/200000722513/file/asus_195eebbae0a44f84b7131bec913a6884.png",
                            ProductId = "pc-gvn-x-asus-evangelion-2"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/5000d_white_aero_d254c2c1d006470dad47a5a4b6c116e8_medium.png",
                            ProductId = "pc-gvn-intel-i7-13700f-vga-rtx-4060-ti"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/ck560_sup_d1bb6e9c38ec4c1f9cdc51376bf69586_medium.png",
                            ProductId = "pc-gvn-intel-i5-13600kf-vga-rtx-3060"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/5000d_white_aero_61797e20d29a47ff9f7589071a5099da_medium.png",
                            ProductId = "pc-gvn-intel-i7-13700f-vga-rtx-4070"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/6969_78b8ac902d2442afa83d968230de5974_medium.png",
                            ProductId = "pc-gvn-intel-i5-12400f-vga-rtx-4060"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/3434_ffad2fc6179e4ab580d39c9b87ada591_medium.png",
                            ProductId = "pc-gvn-intel-i3-12100f-vga-gtx-1650"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/g502x-plus-gallery-2-white_69229c9ba5534ad5bfae7d827037a28f_365394a31b6342e4949249099adb755e_medium.png",
                            ProductId = "chuot-logitech-g502-x-plus-lightspeed-white"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/thumbchuot_8b80210461d64beab28fb3cde34b7280_medium.jpg",
                            ProductId = "chuot-razer-basilisk-v3"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/thumbchuot_a405fadb92a34c429c3eed4d11a84fb5_medium.jpg",
                            ProductId = "chuot-logitech-g-pro-x-superlight-wireless-red"
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/logitech-g102-lightsync-rgb-black-1_bf4f5774229c4a0f81b8e8a2feebe4d8_aeb4ae49ee844c3e9d315883d4e482d4_medium.jpg",
                            ProductId = "chuot-logitech-g102-lightsync-black"
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/h-g304-lightspeed-wireless-white-1000_e28318985b5049099c4e8381695e810f_782b9a4494994a2ea98cf9e699e35200_medium.jpg",
                            ProductId = "chuot-logitech-g304-wireless-white"
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://product.hstatic.net/200000722513/product/gvn_log_g304_3df28cd60a48412b8fb1d2ff762dc6a9_1f12340f2e6b4b8892163de0a06676f2_medium.png",
                            ProductId = "chuot-logitech-g304-wireless"
                        });
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            FirstName = "Admin",
                            HashedPassword = "Rmg+bYlkeE/boUDayWPomveh0YdAXQFdKggn51R8atA=",
                            LastName = "User",
                            Phone = "123-456-7890",
                            Role = 0,
                            Salt = new byte[] { 201, 5, 137, 189, 53, 28, 185, 168, 19, 128, 245, 123, 235, 21, 166, 230 }
                        });
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.CartItem", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamTech_Ecommerce.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Gift", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Product", "Product")
                        .WithMany("Gifts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Order", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamTech_Ecommerce.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Discount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.OrderItem", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamTech_Ecommerce.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Payment", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamTech_Ecommerce.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Product", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.ProductImage", b =>
                {
                    b.HasOne("DreamTech_Ecommerce.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Discount", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Gifts");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("DreamTech_Ecommerce.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
