export const GLOBAL_TYPES={
    MODAL_AUTH:"MODAL_AUTH",
    AUTH:'AUTH',
    MODAL_LOGOUT:'MODAL_LOGOUT',
    ALERT:'ALERT',
    ADD_CART:'ADD_CART',
    GET_CARTS:'GET_CARTS',
    REMOVE_CART:'REMOVE_CART',
    UPDATE_CART:'UPDATE_CART'
  
}